### ISSUE TITLE
about metadata_service_type = SQLMetadataService Startup error

### ISSUE THREAD

**Issue by smallwarm** [teamclairvoyant/airflow-scheduler-failover-controller#43]
scheduler_failover_controller start
/opt/anaconda3/envs/airflow_all/bin/scheduler_failover_controller:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('scheduler-failover-controller==1.0.8')
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_all/bin/scheduler_failover_controller", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/APP/airflow_all/airflow-scheduler-failover-controller-master/scheduler_failover_controller/bin/scheduler_failover_controller", line 7, in <module>
    args.func(args)
  File "/data/APP/airflow_all/airflow-scheduler-failover-controller-master/scheduler_failover_controller/bin/cli.py", line 92, in start
    scheduler_nodes_in_cluster, poll_frequency, metadata_service, emailer, failover_controller = get_all_scheduler_failover_controller_objects()
                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/APP/airflow_all/airflow-scheduler-failover-controller-master/scheduler_failover_controller/bin/cli.py", line 26, in get_all_scheduler_failover_controller_objects
    metadata_service = build_metadata_service(configuration, logger)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/APP/airflow_all/airflow-scheduler-failover-controller-master/scheduler_failover_controller/app.py", line 10, in build_metadata_service
    return SQLMetadataService(
           ^^^^^^^^^^^^^^^^^^^
  File "/data/APP/airflow_all/airflow-scheduler-failover-controller-master/scheduler_failover_controller/metadata/sql_metadata_service.py", line 27, in __init__
    self.engine = create_engine(sql_alchemy_conn, **engine_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/opt/anaconda3/envs/airflow_all/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/airflow_all/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 516, in create_engine
    u, plugins, kwargs = u._instantiate_plugins(kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'

My
 airflow celery worker, airflow scheduler, airflow webserver
You can start the application normally
scheduler_failover_controller init No problem
scheduler_failover_controller test_connection No problem
only
scheduler_failover_controller star Error reporting

I may not be very familiar with Airflow, do you all have the same question

**Comment by longpt233** [comment]
in configuration.py, SQL_ALCHEMY_CONN get from [core] section:     

```
def get_sql_alchemy_conn(self):
        return self.get_config("core", "SQL_ALCHEMY_CONN")
```

but maybe airflow.cfg in new version of airflow, the section has SQL_ALCHEMY_CONN config is [database]. so that engine init from this config can be null

add sql_alchemy_conn both [database], [core] in airflow.cfg can fix this issue
